services:
  backend:
    build: ./back
    container_name: recommender-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./front
    container_name: recommender-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend